# 安装 nginx，如果不用可以注释掉
- name: Nginx
  hosts: lb
  roles:
    - nginx
  tags: nginx

# 初始化环境
- name: Init Environment
  hosts: k8s
  roles:
    - init
  tags: init

# 创建证书
- name: Create Certs
  hosts: local
  roles:
    - cert
  tags: cert

# 安装 etcd
- name: Install Etcd Cluster
  hosts: masters
  roles:
    - etcd
  tags: etcd

# 安装 masters
- name: Install Master Cluster
  hosts: masters
  roles:
    - master
  tags: master

# 安装 nodes
- name: Install Node Cluster
  hosts: nodes
  roles:
    - node
  tags: node

# 安装 网路插件
- name: Install Network Plugins
  hosts: nodes
  roles:
    - { role: flannel, tags: flannel,  when: network_type == 'flannel' }
    - { role: calico, tags: calico,  when: network_type == 'calico' }
  tags: network

# 安装 coredns
- name: Install Coredns 
  hosts: masters
  roles:
    - coredns
  tags: coredns

# 安装 metrics
- name: Install Metrics-server 
  hosts: masters
  roles:
    - metrics-server
  tags: metrics

# 给 masters 节点打标签和污点
- name: Masters -> Label and Tains
  hosts: masters
  roles:
    - label_master
  tags: make_master_labels_and_taints